### ISSUE TITLE
plugins.cloudfoundry.org fell back to very old version?

### ISSUE THREAD

**Issue by michael-on-the-job** [cloudfoundry/cli-plugin-repo#478]
Hello,

it seems the information on https://plugins.cloudfoundry.org/ does not reflect https://github.com/cloudfoundry/cli-plugin-repo/commits/main/

E.g. metric-registrar v.1.3.1 - but it should be already 1.4.3.
For several other plugins too - in fact all entries on current plugins.cloudfoundry.org page are older than year 2022.

You can even verify with web archive:  https://web.archive.org/web/20231118165550/https://plugins.cloudfoundry.org/

Is there anything wrong?

Thanks.

**Comment by a-b** [comment]
Thanks for bringing this to our attention. We're undergoing a major infrastructure migration, and this will be addressed soon.

**Comment by gururajsh** [comment]
This is should be fixed now. Please check and let us know.

**Comment by michael-on-the-job** [comment]
Hello,

thanks for quick actions.

Unfortunately it not yet fixed (only partly):

Fixed:  The textual information seems now to be up-to-date again

But: https://plugins.cloudfoundry.org/list still contains the old download links.

For example metric-registrar is announced as v. 1..4.6, but the actual download link is v. 1.3.1.

:
 {
            "name": "metric-registrar",
            "description": "Allow users to register metric sources.",
            "version": "1.4.6",
            "created": "2018-10-04T18:21:00Z",
            "updated": "2024-04-09T00:00:00Z",
            "company": "VMware",
            "authors": [{
                    "name": "CF Metric Registrar Team",
                    "homepage": "",
                    "contact": ""
                }
            ],
            "homepage": "https://github.com/pivotal-cf/metric-registrar-cli",
            "binaries": [{
                    "platform": "osx",
                    "url": "https://github.com/pivotal-cf/metric-registrar-cli/releases/download/1.3.1/metric-registrar-cli-darwin-amd64-1.3.1",
                    "checksum": "052cee36922814740b199e309c20c68e616ada4e"
                }, {
                    "platform": "win64",
                    "url": "https://github.com/pivotal-cf/metric-registrar-cli/releases/download/1.3.1/metric-registrar-cli-windows-amd64-1.3.1",
                    "checksum": "74f8fb94a7da51a170fb985b279309c49a9171e3"
                }, {
                    "platform": "win32",
                    "url": "https://github.com/pivotal-cf/metric-registrar-cli/releases/download/1.3.1/metric-registrar-cli-windows-386-1.3.1",
                    "checksum": "9a2190bc1de2e13edeb93ae205e08b74139d071c"
                }, {
                    "platform": "linux64",
                    "url": "https://github.com/pivotal-cf/metric-registrar-cli/releases/download/1.3.1/metric-registrar-cli-linux-amd64-1.3.1",
                    "checksum": "341cd87902cdc0abb39c85b42aa4fe52446b5cb7"
                }, {
                    "platform": "linux32",
                    "url": "https://github.com/pivotal-cf/metric-registrar-cli/releases/download/1.3.1/metric-registrar-cli-linux-386-1.3.1",
                    "checksum": "87de0637480d32e391b5f167dc92bb526135db47"
                }
            ]
  :

**Comment by michael-on-the-job** [comment]
To me it seems to be fixed now. 

I reviewed some of the plugins: The information in the description and the download links (also https://plugins.cloudfoundry.org/list) seems to be consistent and up-to-date now.

Thanks.
